name: docket
description: "A Cross Platform Document Tracking Application"
publish_to: "none"
version: 0.1.0

flutter:
  assets:
    - .env
  uses-material-design: true

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  flutter_dotenv: ^5.2.1
  supabase_flutter: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
